language: ruby
rvm:
  - 2.3.5
cache:
  - bundler
  - yarn
dist: trusty
addons:
  chrome: stable
before_script:
  - psql -c 'create database ferret_test;' -U postgres
script:
  - bin/rails assets:precompile
  - bin/rails test:system
  - bin/rails test
  - bundle exec rspec
