language: ruby
rvm:
  - 2.3.5
addons:
  apt:
    packages:
      - google-chrome-stable
      - chromium-chromedriver
cache:
  - bundler
  - yarn
before_script:
  - psql -c 'create database ferret_test;' -U postgres
  - webdriver-manager update --versions.chrome=2.37
script:
  - bin/rails assets:precompile
  - bin/rails test
  - bin/rails test:system
  - bundle exec rspec
