language: ruby
rvm:
  - 2.4.4
cache:
  bundler: true
  directories:
  - npm_modules
# Workaround for https://github.com/travis-ci/travis-ci/issues/8836
# sudo: false
sudo: required
dist: trusty
addons:
  chrome: stable
before_script:
  - psql -c 'create database ferret_test;' -U postgres
script:
  - bin/rails assets:precompile
  - bundle exec rspec
  - bin/rails test:system
