language: ruby
rvm:
  - 2.5.8
cache:
  bundler: true
  directories:
    - node_modules
bundler_args: --without production
dist: bionic
services:
  - postgresql
addons:
  chrome: stable
before_install:
  - yes | gem update --system --force
  - gem install bundler
before_script:
  - psql -c 'create database ferret_test;' -U postgres
script:
  - bin/rails assets:precompile
  - bundle exec rspec
  - bin/rails test:system
