language: ruby
rvm:
  - 2.3.5
cache:
  - bundler
  - yarn
before_script:
  - psql -c 'create database ferret_test;' -U postgres
script:
  - bin/rails assets:precompile
  - bin/rails test
  - bundle exec rspec
