language: ruby
rvm:
  - 2.5.8
cache:
  bundler: true
  directories:
    - npm_modules
bundler_args: --without production
# Workaround for https://github.com/travis-ci/travis-ci/issues/8836
# sudo: false
sudo: required
dist: xenial
addons:
  chrome: beta
before_install:
  - yes | gem update --system --force
  - gem install bundler
# https://travis-ci.community/t/how-to-setup-chromedriver-74-with-chrome-74-for-travis/2678/3
before_script:
  - RAILS_ENV=test bin/rails webdrivers:chromedriver:update
  - psql -c 'create database ferret_test;' -U postgres
script:
  - bin/rails assets:precompile
  - bundle exec rspec
  - bin/rails test:system
